service: TurfTrackerService

# Serverless plugins
plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            # TODO: make this arn dynamic
            - arn:aws:dynamodb:us-east-1:274548839274:table/TurfTracker-dev


# functions
functions:
  api:
    handler: src/index.handler
    events: # The events that trigger this function
      - httpApi: '*'

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

resources:
  Resources:
    dynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TurfTracker-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema: 
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
