service: TurfTrackerService

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

# functions
functions:
  api:
    handler: src/index.handler
    events: # The events that trigger this function
      - httpApi: '*'

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline