service: TurfTrackerService

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

# functions
functions:
  api:
    handler: src/index.handler
    events: # The events that trigger this function
      - httpApi: 
          path: '*'
          method: '*'

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline